main/default/objects/Cocktail__c/Cocktail__c.object-meta.xml
<CustomObject>
    <label>Cocktail</label>
    <nameField>
        <label>Cocktail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cocktails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Cocktail__c/fields/Picture__c.field-meta.xml
<CustomField>
    <fullName>Picture__c</fullName>
    <formula>&quot;/cocktails/&quot; &amp; SUBSTITUTE(Name, &quot; &quot;, &quot;&quot;) &amp; &quot;.jpg&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Picture</label>
    <type>Text</type>
</CustomField>

main/default/objects/CocktailItem__c/CocktailItem__c.object-meta.xml
<CustomObject>
    <label>CocktailItem</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>CocktailItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CocktailItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/CocktailItem__c/fields/Cocktail__c.field-meta.xml
<CustomField>
    <fullName>Cocktail__c</fullName>
    <label>Cocktail</label>
    <referenceTo>Cocktail__c</referenceTo>
    <relationshipLabel>Cocktail components</relationshipLabel>
    <relationshipName>CocktailItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/CocktailItem__c/fields/Component__c.field-meta.xml
<CustomField>
    <fullName>Component__c</fullName>
    <label>Component</label>
    <referenceTo>Component__c</referenceTo>
    <relationshipLabel>CocktailItems</relationshipLabel>
    <relationshipName>CocktailItems</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Component__c/Component__c.object-meta.xml
<CustomObject>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/classes/CocktailController.cls
public with sharing class CocktailController {
    @AuraEnabled(cacheable=true)
    public static List<CocktailWrapper> getCocktailList() {
        List<CocktailWrapper> returnList = new List<CocktailWrapper>();
        List<Cocktail__c> cocktails = [SELECT 
            Name, 
            Description__c,
            Picture__c, 
            (SELECT Component__r.Name FROM CocktailItems__r) 
            FROM Cocktail__c
            ORDER BY Name ASC NULLS LAST];
        for(Cocktail__c coc : cocktails) {
           List<String> items = new List<String>();
           for(CocktailItem__c cI : coc.CocktailItems__r) {
                items.add(cI.Component__r.Name);
            }
            CocktailWrapper cocktail = new CocktailWrapper();
            cocktail.Id = coc.Id;
            cocktail.Name = coc.Name;
            cocktail.ingridients = items;
            cocktail.Description = coc.Description__c;
            cocktail.Picture = coc.Picture__c;
            returnList.add(cocktail);
        }
        return returnList;
    }

    @AuraEnabled(cacheable=true)
    public static List<Component__c> getIngridientsList() {
    
        return [SELECT Name FROM Component__c ORDER BY Name ASC NULLS LAST];
    }

    
    public class CocktailWrapper {
        @AuraEnabled 
        public String Id;
        @AuraEnabled 
        public String Name;
        @AuraEnabled 
        public List<String> ingridients;
        @AuraEnabled 
        public String Description;
        @AuraEnabled 
        public String picture;
    }
}